### PR TITLE
added DryRun to asset

### PR DESCRIPTION
**Pull request by SmartCat**

### CODE REVIEW

**Comment by geron-cn** [comment]
Thank very much, you are so nice.

**Comment by geron-cn** [comment]
But in this way, it still initialize some glprogram shaders in `new GAFAsset()`. 
And i think you can remove the `static` which in the head of the functions while you use a new GAFAsset's data to get reference files.

**Comment by SmartCat** [comment]
Hello,
I've changed behavior in GAFAsset constructor.
What about static specifier, I'll think about it. But exactly now I prefer to leave this specifier ;)

**Comment by geron-cn** [comment]
Nice work      _^_^_

**Pull request merged**
